#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("Layer3_Neurons_CPU_hls_address0", 11, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("Layer3_Neurons_CPU_hls_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("Layer3_Neurons_CPU_hls_q0", 16, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("Layer3_Neurons_CPU_hls_address1", 11, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("Layer3_Neurons_CPU_hls_ce1", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("Layer3_Neurons_CPU_hls_q1", 16, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("Layer3_Weights_CPU_hls_address0", 11, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("Layer3_Weights_CPU_hls_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("Layer3_Weights_CPU_hls_q0", 16, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("Layer3_Weights_CPU_hls_address1", 11, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("Layer3_Weights_CPU_hls_ce1", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("Layer3_Weights_CPU_hls_q1", 16, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("Layer4_Neurons_CPU_hls_address0", 7, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("Layer4_Neurons_CPU_hls_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("Layer4_Neurons_CPU_hls_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("Layer4_Neurons_CPU_hls_d0", 16, hls_out, 2, "ap_memory", "mem_din", 1),
};
const char* HLS_Design_Meta::dut_name = "calculateLayer4";
