#pragma line 1 "DeepLearningHLS/layer4_hls.c" ::: 0
#pragma line 1 "DeepLearningHLS/layer4_hls.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 148 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "D:/Vivado_HLS/2016.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 283 "D:/Vivado_HLS/2016.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 64
#pragma line 421 "D:/Vivado_HLS/2016.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 191
#pragma line 7 "<command line>" 2 ::: 193
#pragma line 1 "<built-in>" 2 ::: 194
#pragma line 1 "DeepLearningHLS/layer4_hls.c" 2 ::: 195
#pragma line 1 "DeepLearningHLS/layer4_hls.h" 1 ::: 196
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 1 3 4 ::: 200
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 1 3 4 ::: 234
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 4 ::: 263
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 4 ::: 274
#pragma line 18 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 4 ::: 280
#pragma line 47 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 4 ::: 285
#pragma line 62 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 4 ::: 287
#pragma line 79 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 4 ::: 294
#pragma line 10 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 4 ::: 297
#pragma line 32 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 301
#pragma line 147 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 304
#pragma line 225 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 308
#pragma line 277 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 310
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 4 ::: 311
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 4 ::: 325
#pragma line 674 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 331
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 4 ::: 332
#pragma line 674 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 4 ::: 333
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 4 ::: 335
#pragma line 675 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 4 ::: 336
#pragma line 13 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 4 ::: 337
#pragma line 46 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 4 ::: 357
#pragma line 102 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 4 ::: 359
#pragma line 277 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 4 ::: 361
#pragma line 316 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 365
#pragma line 372 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 371
#pragma line 382 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 373
#pragma line 394 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 375
#pragma line 407 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 377
#pragma line 420 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 379
#pragma line 456 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 398
#pragma line 518 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 416
#pragma line 605 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 4 ::: 430
#pragma line 28 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 2 3 4 ::: 494
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 499
#pragma line 56 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 540
#pragma line 32 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 2 3 4 ::: 543
#pragma line 90 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 3 4 ::: 587
#pragma line 106 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 3 4 ::: 589
#pragma line 122 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 3 4 ::: 591
#pragma line 134 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 3 4 ::: 594
#pragma line 164 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 3 4 ::: 601
#pragma line 33 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 2 3 4 ::: 642
#pragma line 5 "DeepLearningHLS/layer4_hls.h" 2 ::: 643
#pragma line 2 "DeepLearningHLS/layer4_hls.c" 2 ::: 654
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 655
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 665
#pragma line 9 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 671
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 674
#pragma line 11 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 682
#pragma line 26 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 686
#pragma line 84 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 698
#pragma line 108 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 711
#pragma line 120 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 713
#pragma line 157 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 715
#pragma line 312 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 861
#pragma line 330 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 869
#pragma line 373 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 905
#pragma line 417 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 940
#pragma line 475 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 970
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 1006
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 1016
#pragma line 9 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 1022
#pragma line 509 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1023
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 1026
#pragma line 511 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1034
#pragma line 3 "DeepLearningHLS/layer4_hls.c" 2 ::: 1035
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 1 3 ::: 1036
#pragma line 10 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1047
#pragma line 1 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 1050
#pragma line 12 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 2 3 ::: 1056
#pragma line 55 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1062
#pragma line 79 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1067
#pragma line 91 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1069
#pragma line 135 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1103
#pragma line 162 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1122
#pragma line 236 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1182
#pragma line 260 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1184
#pragma line 278 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1191
#pragma line 325 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1216
#pragma line 372 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1230
#pragma line 403 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1238
#pragma line 552 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1360
#pragma line 583 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1382
#pragma line 594 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1384
#pragma line 737 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1454
#pragma line 867 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1550
#pragma line 898 "D:/Vivado_HLS/2016.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\math.h" 3 ::: 1566
#pragma line 4 "DeepLearningHLS/layer4_hls.c" 2 ::: 1568
